// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "api-gateway/internal/handler/auth"
	community "api-gateway/internal/handler/community"
	ride "api-gateway/internal/handler/ride"
	user "api-gateway/internal/handler/user"
	vehicle "api-gateway/internal/handler/vehicle"
	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 社区帖子
					Method:  http.MethodGet,
					Path:    "/posts",
					Handler: community.GetPostsHandler(serverCtx),
				},
				{
					// 路书列表
					Method:  http.MethodGet,
					Path:    "/route-books",
					Handler: community.GetRouteBooksHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 开始骑行
					Method:  http.MethodPost,
					Path:    "/rides",
					Handler: ride.StartRideHandler(serverCtx),
				},
				{
					// 骑行记录列表
					Method:  http.MethodGet,
					Path:    "/rides",
					Handler: ride.ListRidesHandler(serverCtx),
				},
				{
					// 骑行详情
					Method:  http.MethodGet,
					Path:    "/rides/:id",
					Handler: ride.GetRideHandler(serverCtx),
				},
				{
					// 结束骑行
					Method:  http.MethodPost,
					Path:    "/rides/:id/finish",
					Handler: ride.FinishRideHandler(serverCtx),
				},
				{
					// 暂停骑行
					Method:  http.MethodPost,
					Path:    "/rides/:id/pause",
					Handler: ride.PauseRideHandler(serverCtx),
				},
				{
					// 上传轨迹点
					Method:  http.MethodPost,
					Path:    "/rides/:id/points",
					Handler: ride.UploadPointsHandler(serverCtx),
				},
				{
					// 继续骑行
					Method:  http.MethodPost,
					Path:    "/rides/:id/resume",
					Handler: ride.ResumeRideHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 当前用户信息
					Method:  http.MethodGet,
					Path:    "/users/me",
					Handler: user.GetMeHandler(serverCtx),
				},
				{
					// 用户骑行统计
					Method:  http.MethodGet,
					Path:    "/users/me/stats",
					Handler: user.GetStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					// 选择座驾
					Method:  http.MethodPost,
					Path:    "/vehicles",
					Handler: vehicle.SelectVehicleHandler(serverCtx),
				},
				{
					// 我的座驾
					Method:  http.MethodGet,
					Path:    "/vehicles/mine",
					Handler: vehicle.GetMyVehicleHandler(serverCtx),
				},
				{
					// 座驾型号列表
					Method:  http.MethodGet,
					Path:    "/vehicles/models",
					Handler: vehicle.GetVehicleModelsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
